import hashlib
import importlib.util
import json
from pathlib import Path

import numpy as np
import pytest


def _statistics_file(tmp_path: Path) -> Path:
    from octo_small_official_pytorch.checkpoint import (
        OFFICIAL_BRIDGE_ACTION_MASK,
        OFFICIAL_BRIDGE_ACTION_MEAN,
        OFFICIAL_BRIDGE_ACTION_STD,
    )

    path = tmp_path / "dataset_statistics.json"
    path.write_text(
        json.dumps(
            {
                "bridge_dataset": {
                    "action": {
                        "mean": list(OFFICIAL_BRIDGE_ACTION_MEAN),
                        "std": list(OFFICIAL_BRIDGE_ACTION_STD),
                        "mask": list(OFFICIAL_BRIDGE_ACTION_MASK),
                    }
                }
            }
        ),
        encoding="utf-8",
    )
    return path


class _Tokenizer:
    def __init__(self):
        self.calls = []

    def __call__(self, instructions, **kwargs):
        self.calls.append((instructions, kwargs))
        return {
            "input_ids": np.arange(16, dtype=np.int64)[None],
            "attention_mask": np.ones((1, 16), dtype=np.int64),
        }


def test_official_statistics_use_mean_std_and_leave_gripper_continuous(tmp_path):
    from octo_small_official_pytorch.checkpoint import (
        OFFICIAL_BRIDGE_ACTION_MEAN,
        OFFICIAL_BRIDGE_ACTION_STD,
    )
    from octo_small_official_pytorch.policy import load_official_action_statistics

    statistics = load_official_action_statistics(_statistics_file(tmp_path))
    normalized = np.ones((1, 4, 7), dtype=np.float32)

    actions = statistics.denormalize_actions(normalized)

    np.testing.assert_allclose(
        actions[0, 0, :6],
        np.asarray(OFFICIAL_BRIDGE_ACTION_MEAN[:6]) + np.asarray(OFFICIAL_BRIDGE_ACTION_STD[:6]),
    )
    assert actions[0, 0, 6] == 1.0
    assert statistics.as_dict()["dataset_name"] == "bridge_dataset"


def test_statistics_loader_rejects_non_released_bridge_values(tmp_path):
    from octo_small_official_pytorch.policy import load_official_action_statistics
    from simpler_bridge.evaluation import SimplerEvaluationError

    path = _statistics_file(tmp_path)
    document = json.loads(path.read_text(encoding="utf-8"))
    document["bridge_dataset"]["action"]["mean"][0] = 0.0
    path.write_text(json.dumps(document), encoding="utf-8")

    with pytest.raises(SimplerEvaluationError, match="released Octo-small"):
        load_official_action_statistics(path)


def test_tensorflow_lanczos3_resize_matches_pinned_simpler_reference():
    from octo_small_official_pytorch.policy import resize_image_tensorflow_lanczos3

    y, x = np.indices((480, 640), dtype=np.int64)
    image = np.stack(
        (
            (3 * y + 5 * x) % 256,
            (11 * y + 7 * x + 13) % 256,
            (17 * y + 19 * x + 29) % 256,
        ),
        axis=-1,
    ).astype(np.uint8)

    resized = resize_image_tensorflow_lanczos3(image, size=(256, 256))

    # Generated by pinned SimplerEnv's tf.image.resize(lanczos3, antialias=True),
    # followed by round/clip/uint8, for the deterministic 480x640 input above.
    assert hashlib.sha256(resized.tobytes()).hexdigest() == (
        "7185cc4c8360d6c9d80aaf180c298e5d327a71b8c3379f8ef69608a387c4abd6"
    )


def test_official_t5_tokenizer_content_hashes_are_pinned():
    from octo_small_official_pytorch.checkpoint import OFFICIAL_T5_CONTENT_SHA256

    assert OFFICIAL_T5_CONTENT_SHA256 == {
        "text_encoder/tokenizer.json": (
            "d2acde0d8d71dd30a711834b07781b9c89feaac33fd332f60507699282740066"
        ),
        "text_encoder/spiece.model": (
            "d60acb128cf7b7f2536e8f38a5b18a05535c9e14c7a355904270e15b0945ea86"
        ),
    }


def test_episode_history_grows_to_two_frames_and_reset_prevents_leakage(tmp_path):
    from octo_small_official_pytorch.policy import (
        OctoOfficialModelPolicy,
        load_official_action_statistics,
    )

    tokenizer = _Tokenizer()
    policy = OctoOfficialModelPolicy(
        model=object(),
        tokenizer=tokenizer,
        statistics=load_official_action_statistics(_statistics_file(tmp_path)),
        device="cpu",
        precision="fp32",
        sampler=lambda prepared, generator: np.zeros((1, 4, 7), dtype=np.float32),
        generator_factory=lambda device, seed: (device, seed),
    )
    first = np.zeros((12, 20, 3), dtype=np.uint8)
    second = np.full((12, 20, 3), 255, dtype=np.uint8)

    policy.begin_episode("Pick up the object")
    prepared_one = policy.prepare_observation(first, "Pick up the object")
    prepared_two = policy.prepare_observation(second, "Pick up the object")

    assert set(prepared_one) == {
        "image_primary",
        "timestep_pad_mask",
        "language_input_ids",
        "language_attention_mask",
    }
    assert prepared_one["image_primary"].shape == (1, 1, 3, 256, 256)
    assert prepared_two["image_primary"].shape == (1, 2, 3, 256, 256)
    assert "proprio" not in prepared_two
    assert tokenizer.calls[0][0] == ["Pick up the object"]
    assert len(tokenizer.calls) == 1

    policy.begin_episode("Place the object")
    prepared_reset = policy.prepare_observation(second, "Place the object")

    assert prepared_reset["image_primary"].shape == (1, 1, 3, 256, 256)
    assert len(tokenizer.calls) == 2
    assert policy.make_generator(7) == ("cpu", 7)


def test_policy_output_is_strictly_horizon_four_and_batch_never_has_proprio(tmp_path):
    from octo_small_official_pytorch.policy import (
        OctoOfficialModelPolicy,
        load_official_action_statistics,
    )

    observed = []

    def sample(prepared, generator):
        observed.append((prepared, generator))
        result = np.zeros((1, 4, 7), dtype=np.float32)
        result[..., 6] = 0.75
        return result

    policy = OctoOfficialModelPolicy(
        model=object(),
        tokenizer=_Tokenizer(),
        statistics=load_official_action_statistics(_statistics_file(tmp_path)),
        device="cpu",
        precision="fp32",
        sampler=sample,
    )
    policy.begin_episode("instruction")
    prepared = policy.prepare_observation(np.zeros((32, 32, 3), dtype=np.uint8), "instruction")
    actions = policy.predict_actions(prepared, generator="rng")

    assert actions.shape == (1, 4, 7)
    assert "proprio" not in observed[0][0]
    assert actions[0, 0, 6] == 0.75
    assert policy.protocol_metadata()["use_proprio"] is False
    assert policy.protocol_metadata()["image_history_horizon"] == 2


def test_finetuned_policy_metadata_is_distinct_from_official_parity(tmp_path):
    from octo_small_official_pytorch.policy import (
        OctoOfficialModelPolicy,
        load_official_action_statistics,
    )

    parity = OctoOfficialModelPolicy(
        model=object(),
        tokenizer=_Tokenizer(),
        statistics=load_official_action_statistics(_statistics_file(tmp_path)),
        device="cpu",
        precision="fp32",
    )
    finetuned = OctoOfficialModelPolicy(
        model=object(),
        tokenizer=_Tokenizer(),
        statistics=load_official_action_statistics(_statistics_file(tmp_path)),
        device="cpu",
        precision="fp32",
        baseline="official_finetuned",
    )

    assert parity.protocol_metadata()["baseline"] == "official_parity"
    assert finetuned.protocol_metadata()["baseline"] == "official_finetuned"


@pytest.mark.parametrize("shape", ((1, 8, 7), (4, 7), (1, 4, 6)))
def test_policy_rejects_non_official_action_shape(tmp_path, shape):
    from octo_small_official_pytorch.policy import (
        OctoOfficialModelPolicy,
        load_official_action_statistics,
    )
    from simpler_bridge.evaluation import SimplerEvaluationError

    policy = OctoOfficialModelPolicy(
        model=object(),
        tokenizer=_Tokenizer(),
        statistics=load_official_action_statistics(_statistics_file(tmp_path)),
        device="cpu",
        precision="fp32",
        sampler=lambda prepared, generator: np.zeros(shape, dtype=np.float32),
    )
    policy.begin_episode("instruction")
    prepared = policy.prepare_observation(np.zeros((32, 32, 3), dtype=np.uint8), "instruction")

    with pytest.raises(SimplerEvaluationError, match=r"expected \(1, 4, 7\)"):
        policy.predict_actions(prepared, generator=None)


def test_horizon_four_ensemble_matches_reference_and_binarizes_after_average():
    from octo_small_official_pytorch.action_ensemble import (
        OfficialTemporalActionEnsembler,
    )
    from simpler_bridge.evaluation import bridge_actions_to_simpler

    ensemble = OfficialTemporalActionEnsembler()
    first = np.zeros((1, 4, 7), dtype=np.float32)
    first[0, 1, 0] = 2.0
    first[0, 1, 6] = 0.49
    second = np.zeros((1, 4, 7), dtype=np.float32)
    second[0, 0, 1] = 4.0
    second[0, 0, 6] = 0.9

    np.testing.assert_array_equal(ensemble.select_action(first), first[0, 0])
    selected = ensemble.select_action(second)

    np.testing.assert_allclose(
        selected,
        [1, 2, 0, 0, 0, 0, 0.695],
        rtol=0,
        atol=1e-7,
    )
    assert bridge_actions_to_simpler(selected, gripper_threshold=0.5)[6] == 1


def test_horizon_four_ensemble_matches_pinned_simpler_reference():
    from octo_small_official_pytorch.action_ensemble import (
        OfficialTemporalActionEnsembler,
    )

    source = (
        Path(__file__).resolve().parents[1]
        / "third_party"
        / "SimplerEnv"
        / "simpler_env"
        / "utils"
        / "action"
        / "action_ensemble.py"
    )
    spec = importlib.util.spec_from_file_location("official_h4_ensemble", source)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    reference = module.ActionEnsembler(pred_action_horizon=4, action_ensemble_temp=0.0)
    implementation = OfficialTemporalActionEnsembler()
    rng = np.random.default_rng(17)

    for _ in range(8):
        actions = rng.normal(size=(1, 4, 7)).astype(np.float32)
        np.testing.assert_allclose(
            implementation.select_action(actions),
            reference.ensemble_action(actions[0]),
            rtol=1e-6,
            atol=1e-6,
        )


def test_remote_policy_ignores_runner_proprio_and_resets_server_episode():
    from octo_small_official_pytorch.ipc import IPC_PROTOCOL_VERSION
    from octo_small_official_pytorch.remote_policy import OctoOfficialRemotePolicy

    class Client:
        def __init__(self):
            self.episodes = []
            self.calls = []

        def metadata(self):
            return {
                "protocol_version": IPC_PROTOCOL_VERSION,
                "protocol_name": "octo-small-official-pytorch-ipc-v1",
                "native_action_chunk_size": 4,
                "action_dim": 7,
                "image_history_horizon": 2,
                "use_proprio": False,
                "device": "cuda:4",
                "checkpoint": {},
                "protocol": {"model_action_gripper": "continuous_model_prediction"},
                "startup_preflight": {"action_shape": [1, 4, 7]},
            }

        def reset_rng(self, seed):
            return seed

        def begin_episode(self, instruction):
            self.episodes.append(instruction)

        def infer(self, image, instruction):
            self.calls.append((image, instruction))
            return np.zeros((1, 4, 7), dtype=np.float32)

    client = Client()
    policy = OctoOfficialRemotePolicy(client)
    image = np.zeros((64, 64, 3), dtype=np.uint8)
    policy.begin_episode("instruction")
    prepared = policy.prepare_observation(image, np.arange(8), "instruction")
    actions = policy.predict_actions(prepared, generator=0)

    assert client.episodes == ["instruction"]
    assert set(prepared) == {"image", "instruction"}
    assert client.calls == [(image, "instruction")]
    assert actions.shape == (1, 4, 7)
    assert policy.model_device == "cuda:4"
    assert policy.protocol_metadata()["gripper_binarization"] == "after_action_ensemble"
